/*************************************************************************
 *
 * Copyright 2010 ThanLwinSoft.org
 *
 * This file is part of the ThanLwinSoft Myanmar Extension for OpenOffice.org.
 *
 * This extension is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License version 3
 * only, as published by the Free Software Foundation.
 *
 * This extension is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License version 3 for more details
 * (a copy is included in the LICENSE file that accompanied this code).
 *
 * You should have received a copy of the GNU Lesser General Public License
 * version 3 along with OpenOffice.org.  If not, see
 * <http://www.openoffice.org/license.html>
 * for a copy of the LGPLv3 License.
 *
 ************************************************************************/


#include "MyanmarBreak.hxx"

using namespace org::thanlwinsoft::myanmar;

const int MyanmarBreak::MY_BASE = 0x1000;

const int MyanmarBreak::PAIR_TABLE[MyanmarBreak::MY_SYLLABLE_NUM_PARTS]
    [MyanmarBreak::MY_SYLLABLE_NUM_PARTS] = {
    // first char as row, second as column
    // 0=illegal, 1=no, 2=yes, 3=yes-line, 4=punctuation, 5=context,
    //-  C  M  V  T 39 3A  N  S
    { 1, 3, 1, 1, 1, 1, 1, 1, 1 },//-
    { 3, 5, 1, 1, 1, 1, 1, 2, 4 },//C
    { 3, 5, 1, 1, 1, 0, 1, 2, 4 },//M
    { 3, 5, 0, 1, 1, 0, 1, 2, 4 },//V
    { 3, 2, 0, 1, 1, 0, 1, 2, 4 },//T
    { 3, 1, 0, 0, 0, 0, 0, 0, 0 },//1039
    { 3, 2, 1, 1, 1, 1, 0, 2, 4 },//103A
    { 3, 2, 1, 1, 1, 0, 0, 1, 4 },//N
    { 3, 2, 0, 0, 0, 0, 0, 2, 0 }//S
};

const MyanmarBreak::MySyllablePart MyanmarBreak::CHAR_PART[0xA0] = {
MY_SYLLABLE_CONSONANT,//1000;MYANMAR LETTER KA;Lo;0;L;;;;;N;;;;;
MY_SYLLABLE_CONSONANT,//1001;MYANMAR LETTER KHA;Lo;0;L;;;;;N;;;;;
MY_SYLLABLE_CONSONANT,//1002;MYANMAR LETTER GA;Lo;0;L;;;;;N;;;;;
MY_SYLLABLE_CONSONANT,//1003;MYANMAR LETTER GHA;Lo;0;L;;;;;N;;;;;
MY_SYLLABLE_CONSONANT,//1004;MYANMAR LETTER NGA;Lo;0;L;;;;;N;;;;;
MY_SYLLABLE_CONSONANT,//1005;MYANMAR LETTER CA;Lo;0;L;;;;;N;;;;;
MY_SYLLABLE_CONSONANT,//1006;MYANMAR LETTER CHA;Lo;0;L;;;;;N;;;;;
MY_SYLLABLE_CONSONANT,//1007;MYANMAR LETTER JA;Lo;0;L;;;;;N;;;;;
MY_SYLLABLE_CONSONANT,//1008;MYANMAR LETTER JHA;Lo;0;L;;;;;N;;;;;
MY_SYLLABLE_CONSONANT,//1009;MYANMAR LETTER NYA;Lo;0;L;;;;;N;;;;;
MY_SYLLABLE_CONSONANT,//100A;MYANMAR LETTER NNYA;Lo;0;L;;;;;N;;;;;
MY_SYLLABLE_CONSONANT,//100B;MYANMAR LETTER TTA;Lo;0;L;;;;;N;;;;;
MY_SYLLABLE_CONSONANT,//100C;MYANMAR LETTER TTHA;Lo;0;L;;;;;N;;;;;
MY_SYLLABLE_CONSONANT,//100D;MYANMAR LETTER DDA;Lo;0;L;;;;;N;;;;;
MY_SYLLABLE_CONSONANT,//100E;MYANMAR LETTER DDHA;Lo;0;L;;;;;N;;;;;
MY_SYLLABLE_CONSONANT,//100F;MYANMAR LETTER NNA;Lo;0;L;;;;;N;;;;;
MY_SYLLABLE_CONSONANT,//1010;MYANMAR LETTER TA;Lo;0;L;;;;;N;;;;;
MY_SYLLABLE_CONSONANT,//1011;MYANMAR LETTER THA;Lo;0;L;;;;;N;;;;;
MY_SYLLABLE_CONSONANT,//1012;MYANMAR LETTER DA;Lo;0;L;;;;;N;;;;;
MY_SYLLABLE_CONSONANT,//1013;MYANMAR LETTER DHA;Lo;0;L;;;;;N;;;;;
MY_SYLLABLE_CONSONANT,//1014;MYANMAR LETTER NA;Lo;0;L;;;;;N;;;;;
MY_SYLLABLE_CONSONANT,//1015;MYANMAR LETTER PA;Lo;0;L;;;;;N;;;;;
MY_SYLLABLE_CONSONANT,//1016;MYANMAR LETTER PHA;Lo;0;L;;;;;N;;;;;
MY_SYLLABLE_CONSONANT,//1017;MYANMAR LETTER BA;Lo;0;L;;;;;N;;;;;
MY_SYLLABLE_CONSONANT,//1018;MYANMAR LETTER BHA;Lo;0;L;;;;;N;;;;;
MY_SYLLABLE_CONSONANT,//1019;MYANMAR LETTER MA;Lo;0;L;;;;;N;;;;;
MY_SYLLABLE_CONSONANT,//101A;MYANMAR LETTER YA;Lo;0;L;;;;;N;;;;;
MY_SYLLABLE_CONSONANT,//101B;MYANMAR LETTER RA;Lo;0;L;;;;;N;;;;;
MY_SYLLABLE_CONSONANT,//101C;MYANMAR LETTER LA;Lo;0;L;;;;;N;;;;;
MY_SYLLABLE_CONSONANT,//101D;MYANMAR LETTER WA;Lo;0;L;;;;;N;;;;;
MY_SYLLABLE_CONSONANT,//101E;MYANMAR LETTER SA;Lo;0;L;;;;;N;;;;;
MY_SYLLABLE_CONSONANT,//101F;MYANMAR LETTER HA;Lo;0;L;;;;;N;;;;;
MY_SYLLABLE_CONSONANT,//1020;MYANMAR LETTER LLA;Lo;0;L;;;;;N;;;;;
MY_SYLLABLE_CONSONANT,//1021;MYANMAR LETTER A;Lo;0;L;;;;;N;;;;;
MY_SYLLABLE_CONSONANT,//1022;MYANMAR LETTER SHAN A;Lo;0;L;;;;;N;;;;;
MY_SYLLABLE_CONSONANT,//1023;MYANMAR LETTER I;Lo;0;L;;;;;N;;;;;
MY_SYLLABLE_CONSONANT,//1024;MYANMAR LETTER II;Lo;0;L;;;;;N;;;;;
MY_SYLLABLE_CONSONANT,//1025;MYANMAR LETTER U;Lo;0;L;;;;;N;;;;;
MY_SYLLABLE_CONSONANT,//1026;MYANMAR LETTER UU;Lo;0;L;1025 102E;;;;N;;;;;
MY_SYLLABLE_CONSONANT,//1027;MYANMAR LETTER E;Lo;0;L;;;;;N;;;;;
MY_SYLLABLE_CONSONANT,//1028;MYANMAR LETTER MON E;Lo;0;L;;;;;N;;;;;
MY_SYLLABLE_CONSONANT,//1029;MYANMAR LETTER O;Lo;0;L;;;;;N;;;;;
MY_SYLLABLE_CONSONANT,//102A;MYANMAR LETTER AU;Lo;0;L;;;;;N;;;;;
MY_SYLLABLE_VOWEL,//102B;MYANMAR VOWEL SIGN TALL AA;Mc;0;L;;;;;N;;;;;
MY_SYLLABLE_VOWEL,//102C;MYANMAR VOWEL SIGN AA;Mc;0;L;;;;;N;;;;;
MY_SYLLABLE_VOWEL,//102D;MYANMAR VOWEL SIGN I;Mn;0;NSM;;;;;N;;;;;
MY_SYLLABLE_VOWEL,//102E;MYANMAR VOWEL SIGN II;Mn;0;NSM;;;;;N;;;;;
MY_SYLLABLE_VOWEL,//102F;MYANMAR VOWEL SIGN U;Mn;0;NSM;;;;;N;;;;;
MY_SYLLABLE_VOWEL,//1030;MYANMAR VOWEL SIGN UU;Mn;0;NSM;;;;;N;;;;;
MY_SYLLABLE_VOWEL,//1031;MYANMAR VOWEL SIGN E;Mc;0;L;;;;;N;;;;;
MY_SYLLABLE_VOWEL,//1032;MYANMAR VOWEL SIGN AI;Mn;0;NSM;;;;;N;;;;;
MY_SYLLABLE_VOWEL,//1033;MYANMAR VOWEL SIGN MON II;Mn;0;NSM;;;;;N;;;;;
MY_SYLLABLE_VOWEL,//1034;MYANMAR VOWEL SIGN MON O;Mn;0;NSM;;;;;N;;;;;
MY_SYLLABLE_VOWEL,//1035;MYANMAR VOWEL SIGN E ABOVE;Mn;0;NSM;;;;;N;;;;;
MY_SYLLABLE_VOWEL,//1036;MYANMAR SIGN ANUSVARA;Mn;0;NSM;;;;;N;;;;;
MY_SYLLABLE_TONE,//1037;MYANMAR SIGN DOT BELOW;Mn;7;NSM;;;;;N;;;;;
MY_SYLLABLE_TONE,//1038;MYANMAR SIGN VISARGA;Mc;0;L;;;;;N;;;;;
MY_SYLLABLE_1039,//1039;MYANMAR SIGN VIRAMA;Mn;9;NSM;;;;;N;;;;;
MY_SYLLABLE_103A,//103A;MYANMAR SIGN ASAT;Mn;9;NSM;;;;;N;;;;;
MY_SYLLABLE_MEDIAL,//103B;MYANMAR CONSONANT SIGN MEDIAL YA;Mc;0;L;;;;;N;;;;;
MY_SYLLABLE_MEDIAL,//103C;MYANMAR CONSONANT SIGN MEDIAL RA;Mc;0;L;;;;;N;;;;;
MY_SYLLABLE_MEDIAL,//103D;MYANMAR CONSONANT SIGN MEDIAL WA;Mn;0;NSM;;;;;N;;;;;
MY_SYLLABLE_MEDIAL,//103E;MYANMAR CONSONANT SIGN MEDIAL HA;Mn;0;NSM;;;;;N;;;;;
MY_SYLLABLE_CONSONANT,//103F;MYANMAR LETTER GREAT SA;Lo;0;L;;;;;N;;;;;
MY_SYLLABLE_NUMBER,//1040;MYANMAR DIGIT ZERO;Nd;0;L;;0;0;0;N;;;;;
MY_SYLLABLE_NUMBER,//1041;MYANMAR DIGIT ONE;Nd;0;L;;1;1;1;N;;;;;
MY_SYLLABLE_NUMBER,//1042;MYANMAR DIGIT TWO;Nd;0;L;;2;2;2;N;;;;;
MY_SYLLABLE_NUMBER,//1043;MYANMAR DIGIT THREE;Nd;0;L;;3;3;3;N;;;;;
MY_SYLLABLE_NUMBER,//1044;MYANMAR DIGIT FOUR;Nd;0;L;;4;4;4;N;;;;;
MY_SYLLABLE_NUMBER,//1045;MYANMAR DIGIT FIVE;Nd;0;L;;5;5;5;N;;;;;
MY_SYLLABLE_NUMBER,//1046;MYANMAR DIGIT SIX;Nd;0;L;;6;6;6;N;;;;;
MY_SYLLABLE_NUMBER,//1047;MYANMAR DIGIT SEVEN;Nd;0;L;;7;7;7;N;;;;;
MY_SYLLABLE_NUMBER,//1048;MYANMAR DIGIT EIGHT;Nd;0;L;;8;8;8;N;;;;;
MY_SYLLABLE_NUMBER,//1049;MYANMAR DIGIT NINE;Nd;0;L;;9;9;9;N;;;;;
MY_SYLLABLE_SECTION,//104A;MYANMAR SIGN LITTLE SECTION;Po;0;L;;;;;N;;;;;
MY_SYLLABLE_SECTION,//104B;MYANMAR SIGN SECTION;Po;0;L;;;;;N;;;;;
MY_SYLLABLE_CONSONANT,//104C;MYANMAR SYMBOL LOCATIVE;Po;0;L;;;;;N;;;;;
MY_SYLLABLE_CONSONANT,//104D;MYANMAR SYMBOL COMPLETED;Po;0;L;;;;;N;;;;;
MY_SYLLABLE_CONSONANT,//104E;MYANMAR SYMBOL AFOREMENTIONED;Po;0;L;;;;;N;;;;;
MY_SYLLABLE_CONSONANT,//104F;MYANMAR SYMBOL GENITIVE;Po;0;L;;;;;N;;;;;
MY_SYLLABLE_CONSONANT,//1050;MYANMAR LETTER SHA;Lo;0;L;;;;;N;;;;;
MY_SYLLABLE_CONSONANT,//1051;MYANMAR LETTER SSA;Lo;0;L;;;;;N;;;;;
MY_SYLLABLE_CONSONANT,//1052;MYANMAR LETTER VOCALIC R;Lo;0;L;;;;;N;;;;;
MY_SYLLABLE_CONSONANT,//1053;MYANMAR LETTER VOCALIC RR;Lo;0;L;;;;;N;;;;;
MY_SYLLABLE_CONSONANT,//1054;MYANMAR LETTER VOCALIC L;Lo;0;L;;;;;N;;;;;
MY_SYLLABLE_CONSONANT,//1055;MYANMAR LETTER VOCALIC LL;Lo;0;L;;;;;N;;;;;
MY_SYLLABLE_VOWEL,//1056;MYANMAR VOWEL SIGN VOCALIC R;Mc;0;L;;;;;N;;;;;
MY_SYLLABLE_VOWEL,//1057;MYANMAR VOWEL SIGN VOCALIC RR;Mc;0;L;;;;;N;;;;;
MY_SYLLABLE_VOWEL,//1058;MYANMAR VOWEL SIGN VOCALIC L;Mn;0;NSM;;;;;N;;;;;
MY_SYLLABLE_VOWEL,//1059;MYANMAR VOWEL SIGN VOCALIC LL;Mn;0;NSM;;;;;N;;;;;
MY_SYLLABLE_CONSONANT,//105A;MYANMAR LETTER MON NGA;Lo;0;L;;;;;N;;;;;
MY_SYLLABLE_CONSONANT,//105B;MYANMAR LETTER MON JHA;Lo;0;L;;;;;N;;;;;
MY_SYLLABLE_CONSONANT,//105C;MYANMAR LETTER MON BBA;Lo;0;L;;;;;N;;;;;
MY_SYLLABLE_CONSONANT,//105D;MYANMAR LETTER MON BBE;Lo;0;L;;;;;N;;;;;
MY_SYLLABLE_MEDIAL,//105E;MYANMAR CONSONANT SIGN MON MEDIAL NA;Mn;0;NSM;;;;;N;;;;;
MY_SYLLABLE_MEDIAL,//105F;MYANMAR CONSONANT SIGN MON MEDIAL MA;Mn;0;NSM;;;;;N;;;;;
MY_SYLLABLE_MEDIAL,//1060;MYANMAR CONSONANT SIGN MON MEDIAL LA;Mn;0;NSM;;;;;N;;;;;
MY_SYLLABLE_CONSONANT,//1061;MYANMAR LETTER SGAW KAREN SHA;Lo;0;L;;;;;N;;;;;
MY_SYLLABLE_VOWEL,//1062;MYANMAR VOWEL SIGN SGAW KAREN EU;Mc;0;L;;;;;N;;;;;
MY_SYLLABLE_VOWEL,//1063;MYANMAR TONE MARK SGAW KAREN HATHI;Mc;0;L;;;;;N;;;;;
MY_SYLLABLE_VOWEL,//1064;MYANMAR TONE MARK SGAW KAREN KE PHO;Mc;0;L;;;;;N;;;;;
MY_SYLLABLE_CONSONANT,//1065;MYANMAR LETTER WESTERN PWO KAREN THA;Lo;0;L;;;;;N;;;;;
MY_SYLLABLE_CONSONANT,//1066;MYANMAR LETTER WESTERN PWO KAREN PWA;Lo;0;L;;;;;N;;;;;
MY_SYLLABLE_VOWEL,//1067;MYANMAR VOWEL SIGN WESTERN PWO KAREN EU;Mc;0;L;;;;;N;;;;;
MY_SYLLABLE_VOWEL,//1068;MYANMAR VOWEL SIGN WESTERN PWO KAREN UE;Mc;0;L;;;;;N;;;;;
MY_SYLLABLE_TONE,//1069;MYANMAR SIGN WESTERN PWO KAREN TONE-1;Mc;0;L;;;;;N;;;;;
MY_SYLLABLE_TONE,//106A;MYANMAR SIGN WESTERN PWO KAREN TONE-2;Mc;0;L;;;;;N;;;;;
MY_SYLLABLE_TONE,//106B;MYANMAR SIGN WESTERN PWO KAREN TONE-3;Mc;0;L;;;;;N;;;;;
MY_SYLLABLE_TONE,//106C;MYANMAR SIGN WESTERN PWO KAREN TONE-4;Mc;0;L;;;;;N;;;;;
MY_SYLLABLE_TONE,//106D;MYANMAR SIGN WESTERN PWO KAREN TONE-5;Mc;0;L;;;;;N;;;;;
MY_SYLLABLE_CONSONANT,//106E;MYANMAR LETTER EASTERN PWO KAREN NNA;Lo;0;L;;;;;N;;;;;
MY_SYLLABLE_CONSONANT,//106F;MYANMAR LETTER EASTERN PWO KAREN YWA;Lo;0;L;;;;;N;;;;;
MY_SYLLABLE_CONSONANT,//1070;MYANMAR LETTER EASTERN PWO KAREN GHWA;Lo;0;L;;;;;N;;;;;
MY_SYLLABLE_VOWEL,//1071;MYANMAR VOWEL SIGN GEBA KAREN I;Mn;0;NSM;;;;;N;;;;;
MY_SYLLABLE_VOWEL,//1072;MYANMAR VOWEL SIGN KAYAH OE;Mn;0;NSM;;;;;N;;;;;
MY_SYLLABLE_VOWEL,//1073;MYANMAR VOWEL SIGN KAYAH U;Mn;0;NSM;;;;;N;;;;;
MY_SYLLABLE_VOWEL,//1074;MYANMAR VOWEL SIGN KAYAH EE;Mn;0;NSM;;;;;N;;;;;
MY_SYLLABLE_CONSONANT,//1075;MYANMAR LETTER SHAN KA;Lo;0;L;;;;;N;;;;;
MY_SYLLABLE_CONSONANT,//1076;MYANMAR LETTER SHAN KHA;Lo;0;L;;;;;N;;;;;
MY_SYLLABLE_CONSONANT,//1077;MYANMAR LETTER SHAN GA;Lo;0;L;;;;;N;;;;;
MY_SYLLABLE_CONSONANT,//1078;MYANMAR LETTER SHAN CA;Lo;0;L;;;;;N;;;;;
MY_SYLLABLE_CONSONANT,//1079;MYANMAR LETTER SHAN ZA;Lo;0;L;;;;;N;;;;;
MY_SYLLABLE_CONSONANT,//107A;MYANMAR LETTER SHAN NYA;Lo;0;L;;;;;N;;;;;
MY_SYLLABLE_CONSONANT,//107B;MYANMAR LETTER SHAN DA;Lo;0;L;;;;;N;;;;;
MY_SYLLABLE_CONSONANT,//107C;MYANMAR LETTER SHAN NA;Lo;0;L;;;;;N;;;;;
MY_SYLLABLE_CONSONANT,//107D;MYANMAR LETTER SHAN PHA;Lo;0;L;;;;;N;;;;;
MY_SYLLABLE_CONSONANT,//107E;MYANMAR LETTER SHAN FA;Lo;0;L;;;;;N;;;;;
MY_SYLLABLE_CONSONANT,//107F;MYANMAR LETTER SHAN BA;Lo;0;L;;;;;N;;;;;
MY_SYLLABLE_CONSONANT,//1080;MYANMAR LETTER SHAN THA;Lo;0;L;;;;;N;;;;;
MY_SYLLABLE_CONSONANT,//1081;MYANMAR LETTER SHAN HA;Lo;0;L;;;;;N;;;;;
MY_SYLLABLE_MEDIAL,//1082;MYANMAR CONSONANT SIGN SHAN MEDIAL WA;Mn;0;NSM;;;;;N;;;;;
MY_SYLLABLE_VOWEL,//1083;MYANMAR VOWEL SIGN SHAN AA;Mc;0;L;;;;;N;;;;;
MY_SYLLABLE_VOWEL,//1084;MYANMAR VOWEL SIGN SHAN E;Mc;0;L;;;;;N;;;;;
MY_SYLLABLE_VOWEL,//1085;MYANMAR VOWEL SIGN SHAN E ABOVE;Mn;0;NSM;;;;;N;;;;;
MY_SYLLABLE_VOWEL,//1086;MYANMAR VOWEL SIGN SHAN FINAL Y;Mn;0;NSM;;;;;N;;;;;
MY_SYLLABLE_TONE,//1087;MYANMAR SIGN SHAN TONE-2;Mc;0;L;;;;;N;;;;;
MY_SYLLABLE_TONE,//1088;MYANMAR SIGN SHAN TONE-3;Mc;0;L;;;;;N;;;;;
MY_SYLLABLE_TONE,//1089;MYANMAR SIGN SHAN TONE-5;Mc;0;L;;;;;N;;;;;
MY_SYLLABLE_TONE,//108A;MYANMAR SIGN SHAN TONE-6;Mc;0;L;;;;;N;;;;;
MY_SYLLABLE_TONE,//108B;MYANMAR SIGN SHAN COUNCIL TONE-2;Mc;0;L;;;;;N;;;;;
MY_SYLLABLE_TONE,//108C;MYANMAR SIGN SHAN COUNCIL TONE-3;Mc;0;L;;;;;N;;;;;
MY_SYLLABLE_TONE,//108D;MYANMAR SIGN SHAN COUNCIL EMPHATIC TONE;Mn;220;NSM;;;;;N;;;;;
MY_SYLLABLE_CONSONANT,//108E;MYANMAR LETTER RUMAI PALAUNG FA;Lo;0;L;;;;;N;;;;;
MY_SYLLABLE_TONE,//108F;MYANMAR SIGN RUMAI PALAUNG TONE-5;Mc;0;L;;;;;N;;;;;
MY_SYLLABLE_NUMBER,//1090;MYANMAR SHAN DIGIT ZERO;Nd;0;L;;0;0;0;N;;;;;
MY_SYLLABLE_NUMBER,//1091;MYANMAR SHAN DIGIT ONE;Nd;0;L;;1;1;1;N;;;;;
MY_SYLLABLE_NUMBER,//1092;MYANMAR SHAN DIGIT TWO;Nd;0;L;;2;2;2;N;;;;;
MY_SYLLABLE_NUMBER,//1093;MYANMAR SHAN DIGIT THREE;Nd;0;L;;3;3;3;N;;;;;
MY_SYLLABLE_NUMBER,//1094;MYANMAR SHAN DIGIT FOUR;Nd;0;L;;4;4;4;N;;;;;
MY_SYLLABLE_NUMBER,//1095;MYANMAR SHAN DIGIT FIVE;Nd;0;L;;5;5;5;N;;;;;
MY_SYLLABLE_NUMBER,//1096;MYANMAR SHAN DIGIT SIX;Nd;0;L;;6;6;6;N;;;;;
MY_SYLLABLE_NUMBER,//1097;MYANMAR SHAN DIGIT SEVEN;Nd;0;L;;7;7;7;N;;;;;
MY_SYLLABLE_NUMBER,//1098;MYANMAR SHAN DIGIT EIGHT;Nd;0;L;;8;8;8;N;;;;;
MY_SYLLABLE_NUMBER,//1099;MYANMAR SHAN DIGIT NINE;Nd;0;L;;9;9;9;N;;;;;
MY_SYLLABLE_TONE,//109A
MY_SYLLABLE_TONE,//109B
MY_SYLLABLE_TONE,//109C
MY_SYLLABLE_TONE,//109D
MY_SYLLABLE_CONSONANT,//109E;MYANMAR SYMBOL SHAN ONE;So;0;L;;;;;N;;;;;
MY_SYLLABLE_CONSONANT//109F;MYANMAR SYMBOL SHAN EXCLAMATION;So;0;L;;;;;N;;;;;
};

bool MyanmarBreak::isMyanmar(const MMChar c)
{
    // Myanmar and Myanmar Extended-A blocks
    if ((c >= 0x1000 && c < 0x10A0) || (c >= 0xAA60 && c < 0xAA80))
        return true;
    return false;
}

MyanmarBreak::MySyllablePart
MyanmarBreak::getSyllablePart(const MMChar mmChar)
{
    // Myanmar Extended A only uses 2 possible values
    if (mmChar >= 0xAA60 && mmChar < 0xAA7C)
    {
        if (mmChar == 0xAA70 || mmChar == 0xAA7B)
            return MY_SYLLABLE_TONE;
        return MY_SYLLABLE_CONSONANT;
    }
    return MySyllablePart(CHAR_PART[mmChar - MY_BASE]);
}

MyanmarBreak::MyPairStatus
MyanmarBreak::getPairStatus(const MMChar a, const MMChar b)
{
    if (!isMyanmar(a))
        if (!isMyanmar(b))
            return MY_PAIR_NO_BREAK;// is this the choice here?
        else
            return MY_PAIR_SYL_BREAK; // language boundary
    else if (!isMyanmar(b))
        return MY_PAIR_SYL_BREAK; // language boundary

    MySyllablePart aPart = getSyllablePart(a);
    MySyllablePart bPart = getSyllablePart(b);
    MyPairStatus pairStatus = MyPairStatus(PAIR_TABLE[aPart][bPart]);
    return pairStatus;
}

// Is it possible to break before the character at the specified
// index?
bool MyanmarBreak::isBreak(const ::rtl::OUString & text, int32_t position,
                           bool includePunctuation)
{
    if (position <= 0 || position >= text.getLength()) return true;
    MMChar prev = text[position-1];
    MMChar c =text[position];
    MyPairStatus pair = getPairStatus(prev, c);
    switch (pair)
    {
    case MY_PAIR_CONTEXT:
        {
            if (position + 1 < text.getLength())
            {
                MMChar next = text[position+1];
                if (c == 0x102d)
                    return false;
                if (next == 0x1039 || next == 0x103A)
                    return false;
                if (next == 0x1037 && position + 2 < text.getLength())
                {
                    next = text[position+2];
                    if (next == 0x103A)
                        return false;
                }
            }
        }
        // else fall through
    case MY_PAIR_SYL_BREAK:
    case MY_PAIR_WORD_BREAK:
    case MY_SYLLABLE_UNKNOWN:
        return true;
    case MY_PAIR_PUNCTUATION:
        return !includePunctuation;
    default:
        break;
    }
    return false;
}

